spring:
  application:
    name: user-service

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081
  error:
    include-message: never
    include-stacktrace: never

jwt:
  secret: ${JWT_SECRET:uniride-dev-secret-key-must-be-at-least-256-bits-long-change-in-prod}
  expiration-ms: 86400000
  refresh-expiration-ms: 604800000

rate-limit:
  max-tentativas: 5
  janela-minutos: 15

institution-service:
  url: ${INSTITUTION_SERVICE_URL:http://localhost:8082}

app:
  url: ${APP_URL:http://192.168.0.42:8080}

logging:
  level:
    com.uniride: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized
